AWSTemplateFormatVersion: 2010-09-09
Description: LanVu Create template VPC
Resources:
  UdacityVPCUpdate:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "true"
      Tags:
        - Key: name
          Value: myfirsttestvpc
